/* Generated By:JavaCC: Do not edit this line. ABDLParserConstants.java */
package abdl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ABDLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADDRESSBOOK = 5;
  /** RegularExpression Id. */
  int PERSON = 6;
  /** RegularExpression Id. */
  int BIRTHDATE = 7;
  /** RegularExpression Id. */
  int PHONE = 8;
  /** RegularExpression Id. */
  int EMAIL = 9;
  /** RegularExpression Id. */
  int ADDRESS = 10;
  /** RegularExpression Id. */
  int EXTENSION = 11;
  /** RegularExpression Id. */
  int TYPE = 12;
  /** RegularExpression Id. */
  int MOBILE = 13;
  /** RegularExpression Id. */
  int HOME = 14;
  /** RegularExpression Id. */
  int WORK = 15;
  /** RegularExpression Id. */
  int OTHER = 16;
  /** RegularExpression Id. */
  int PLUS = 17;
  /** RegularExpression Id. */
  int LP = 18;
  /** RegularExpression Id. */
  int RP = 19;
  /** RegularExpression Id. */
  int LCP = 20;
  /** RegularExpression Id. */
  int RCP = 21;
  /** RegularExpression Id. */
  int ADDRESSBOOK_NAME = 22;
  /** RegularExpression Id. */
  int PERSON_NAME = 23;
  /** RegularExpression Id. */
  int MONTH = 24;
  /** RegularExpression Id. */
  int DAY = 25;
  /** RegularExpression Id. */
  int YEAR = 26;
  /** RegularExpression Id. */
  int PLAINWORD = 27;
  /** RegularExpression Id. */
  int ALPHA = 28;
  /** RegularExpression Id. */
  int DIGIT = 29;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_ADDRESSBOOK = 1;
  /** Lexical state. */
  int IN_PERSON = 2;
  /** Lexical state. */
  int IN_BIRTHDATE = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"addressbook\"",
    "\"person\"",
    "\"birthdate\"",
    "\"phone\"",
    "\"email\"",
    "\"address\"",
    "\"ext\"",
    "<TYPE>",
    "\"mobile\"",
    "\"home\"",
    "\"work\"",
    "\"other\"",
    "\"+\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "<ADDRESSBOOK_NAME>",
    "<PERSON_NAME>",
    "<MONTH>",
    "<DAY>",
    "<YEAR>",
    "<PLAINWORD>",
    "<ALPHA>",
    "<DIGIT>",
  };

}
